name: Build and Package Go Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # Укажите нужную версию Go

      - name: Build
        run: |
          go build -v -o ./output/todopp ./todopp.go 
          
      - name: Copy additional files
        run: |
          cp -r sql/* ./output/ 
          cp -r html/* ./output/   
          cp -r doc/* ./output/
          cp README.md LICENSE ./output/

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: ./output/
          retention-days: 5