name: Build and Package Go Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # Укажите нужную версию Go

      - name: Build
        run: |
          go build -v -o ./output/todopp ./todopp.go 
          
      - name: Copy additional files
        run: |
          mkdir ./output/sql
          mkdir ./output/html/
          mkdir ./output/doc/
          cp -r sql/* ./output/sql/ 
          cp -r html/* ./output/html/  
          cp -r doc/* ./output/doc/
          cp README.md LICENSE ./output/doc/
          echo "${{ secrets.CONFIG_PROD }}" > ./output/config.json

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package-linux
          path: ./output/
          retention-days: 5

      - name: Remove files from VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST_PROD }}
          username: ${{ secrets.VPS_USER_PROD }}
          password: ${{ secrets.VPS_PASSWORD_PROD }}
          script: rm -rf /usr/local/bin/todopp/bin/

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST_PROD }}
          username: ${{ secrets.VPS_USER_PROD }}
          password: ${{ secrets.VPS_PASSWORD_PROD }}
          source: "./output/*"
          target: "/usr/local/bin/todopp/bin"

      - name: Reboot VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST_PROD }}
          username: ${{ secrets.VPS_USER_PROD }}
          password: ${{ secrets.VPS_PASSWORD_PROD }}
          script: |
            cp -aT /usr/local/bin/todopp/bin/output/ /usr/local/bin/todopp/bin/
            rm -rf /usr/local/bin/todopp/bin/output
            reboot
  
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -v -o ./output/todopp ./todopp.go 
          
      - name: Copy additional files
        run: |
          mkdir ./output/sql
          mkdir ./output/html/
          mkdir ./output/doc/
          cp -r sql/* ./output/sql/ 
          cp -r html/* ./output/html/  
          cp -r doc/* ./output/doc/
          cp README.md ./output/doc/
          cp LICENSE ./output/doc/

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package-windows
          path: ./output/
          retention-days: 5